print('favor inserir os dados de nascimento')
print('favor inserir os dados de nascimento')
dia = input('Dia = ')
mes = input('Mes = ')
ano = input('Ano = ')
print(' ')
print('Voce nasceu no dia '+dia+' de '+mes+' de '+ano+' Correto?')
#print('\033[7;30mVoce nasceu no dia '+dia+' de '+mes+' de '+ano+' Correto?')