numero = str(input('Digite um numero de 0 a 9999: '))
print('unidade: {}'.format(numero[3]))
print('dezena: {}'.format(numero[2]))
print('Centena: {}'.format(numero[1]))
print('milhar: {}'.format(numero[0]))